version: '2'
services:


  postgres_db:
    image: mdillon/postgis:9.5
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - /home/evgeniy/IdeaProjects/drug_and_glass/GlassAndDrugs/src/main/resources/db/migration/init_db:/docker-entrypoint-initdb.d/
    networks:
      spring_cloud:
        aliases:
          - postgres
 
  docker-registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./docker-registry:/var/lib/registry
    networks:
      spring_cloud:
        aliases:
          - docker-registry

networks:
  spring_cloud:
    external: false
